@startuml Multisensor

abstract class ISensor {
    {abstract} is_awake() : bool
    {abstract} get_values() : void
    {abstract} update_configuration() : int
}

abstract class IOZWNetwork {
    {abstract} is_network_ready() : bool
    {abstract} is_awake() : bool
    {abstract} get_values() : void
    {abstract} update_configuration() : int
}

class Multisensor implements ISensor {
    - _temperature : float
    - _relhumidity : float
    - _luminance : float
    - _ultraviolet : float
    - _node_id : int
    + sensor_values : dict
    + configurations : dict

      Multisensor(ISensor, IOZWNetwork, node_id)
    ~ Multisensor()
    + is_awake() : bool
    + get_values() : void
    + update_configuration() : int
    - get_temperature() : void
    - get_relhumidity() : void
    - get_luminance() : void
    - get_ultraviolet() : void
}

class OZWNetwork implements IOZWNetwork {
  + options : obj
  + network : obj
  + nodes : obj
  + ZWaveOption() : options
  + ZWaveNetwork(options): network 
  + ZWaveNode(network) : nodes
}

package Open-ZWave <<Folder>> {
  class ZWaveNode
  class ZWaveNetwork
  class ZWaveOption
}

Multisensor ..> IOZWNetwork
OZWNetwork <|-- ZWaveNetwork
OZWNetwork <|-- ZWaveNode
OZWNetwork <|-- ZWaveOption

@enduml