name: Python-auto-test

on: [push]

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --exclude __init__.py,context.py
      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          export PYTHONPATH=src
          pytest ./tests/tests.py --doctest-modules --junitxml=test-results.xml --cov=. --cov-report=xml --cov-report=html
          export PYTHONPATH=./classes
          pytest ./classes/test_*.py --doctest-modules --junitxml=test-results.xml --cov=. --cov-report=xml --cov-report=html
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-result-rapport-xml
          path: ./test-results.xml
      - name: Archive code coverage results in HTML
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report-html
          path: ./htmlcov/
      - name: Archive code coverage results in XML
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report-xml
          path: ./coverage.xml
